antoin = Owner.create(name: "Antoin")
steven = Owner.create(name: "Steven")
kaylee = Owner.create(name: "KSquared")
sophie = Owner.create(name: "SophieD")
josh = Owner.create(name: "JoshinSince89?")


bulbasaur = Pocketmonster.create(name: "Bulbasaur", image_url: 'http://assets22.pokemon.com/assets/cms2/img/pokedex/full/001.png')
squirtle = Pocketmonster.create(name: "Squirtle", image_url: 'http://assets22.pokemon.com/assets/cms2/img/pokedex/full/007.png')
charmander = Pocketmonster.create(name: "Charmander", image_url: 'http://assets22.pokemon.com/assets/cms2/img/pokedex/full/004.png')
pikachu = Pocketmonster.create(name: "Pikachu", image_url: 'http://assets22.pokemon.com/assets/cms2/img/pokedex/full/025.png')
ninetails = Pocketmonster.create(name: "Ninetales", image_url: 'http://assets22.pokemon.com/assets/cms2/img/pokedex/full/038.png')
charizard = Pocketmonster.create(name: "Charizard", image_url: 'http://assets22.pokemon.com/assets/cms2/img/pokedex/full/006.png')
mew = Pocketmonster.create(name: "Mew", image_url: 'http://assets22.pokemon.com/assets/cms2/img/pokedex/full/151.png')
mewtwo = Pocketmonster.create(name: "Mewtwo", image_url: 'http://assets22.pokemon.com/assets/cms2/img/pokedex/full/150.png')
